import React from 'react';
import { motion } from 'framer-motion';
import { Star, Quote } from 'lucide-react';

const testimonials = [
    {
        name: "Sarah Jenkins",
        role: "Head of Talent, TechFlow",
        content: "TalentSage reduced our time-to-hire by 60%. The AI video screening is a game-changer for high-volume recruitment.",
        avatar: "https://i.pravatar.cc/150?u=sarah"
    },
    {
        name: "Michael Chen",
        role: "CTO, Innovate Solutions",
        content: "The technical evaluation rubrics generated by the AI are incredibly precise. It's like having a senior engineer screen every candidate.",
        avatar: "https://i.pravatar.cc/150?u=michael"
    },
    {
        name: "Elena Rodriguez",
        role: "Recruitment Director, Global Corp",
        content: "The premium design and intuitive workspace make it a joy for our team to use. It's the first tool that recruiters actually love.",
        avatar: "https://i.pravatar.cc/150?u=elena"
    }
];

const Testimonials = () => {
    return (
        <section id="testimonials" className="py-24 bg-gray-50 relative overflow-hidden">
            <div className="container mx-auto px-4">
                <div className="text-center max-w-3xl mx-auto mb-16">
                    <motion.h2
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="text-4xl md:text-5xl font-bold text-gray-900 mb-6"
                    >
                        Trusted by <span className="text-accent-600">Industry Leaders</span>
                    </motion.h2>
                    <p className="text-xl text-gray-600">
                        Join hundreds of forward-thinking companies that are scaling their teams with TalentSage.
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    {testimonials.map((t, index) => (
                        <motion.div
                            key={index}
                            initial={{ opacity: 0, scale: 0.9 }}
                            whileInView={{ opacity: 1, scale: 1 }}
                            viewport={{ once: true }}
                            transition={{ delay: index * 0.1 }}
                            className="bg-white p-8 rounded-3xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow relative"
                        >
                            <Quote className="absolute top-6 right-8 text-primary-100" size={48} />
                            <div className="flex gap-1 mb-4">
                                {[...Array(5)].map((_, i) => (
                                    <Star key={i} size={16} className="fill-yellow-400 text-yellow-400" />
                                ))}
                            </div>
                            <p className="text-gray-700 italic mb-8 relative z-10 leading-relaxed">
                                "{t.content}"
                            </p>
                            <div className="flex items-center gap-4">
                                <img src={t.avatar} alt={t.name} className="w-12 h-12 rounded-full border-2 border-primary-100" />
                                <div>
                                    <div className="font-bold text-gray-900">{t.name}</div>
                                    <div className="text-sm text-gray-500">{t.role}</div>
                                </div>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default Testimonials;
